name: todoapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  drift: ^2.15.0
  drift_sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.12
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_svg: ^2.0.9
  delayed_display: ^2.0.0
  flutter_spinkit: ^5.2.0
  loading_overlay: ^0.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.5

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/logo/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
